# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end


  desc 'Fetch certificates and provisioning profiles'
  lane :fetch_certificates do |options|
    readonly = options[:readonly].nil? ? true : options[:readonly]
    force_for_new_devices = options[:force_for_new_devices].nil? ? false : options[:force_for_new_devices]

    fetch_development_certificates(readonly: readonly, force_for_new_devices: force_for_new_devices)
    fetch_distribution_certificates(readonly: readonly, force_for_new_devices: force_for_new_devices)
  end

  desc 'Fetch development certificates'
  lane :fetch_development_certificates do |options|
      readonly = options[:readonly].nil? ? true : options[:readonly]
      force_for_new_devices = options[:force_for_new_devices].nil? ? false : options[:force_for_new_devices]
  
      match(type: 'development', app_identifier: 'com.thacherhussain.slytherin', readonly: readonly, force_for_new_devices: force_for_new_devices)
      # match(type: 'development', app_identifier: 'com.frandepascuali.time.beta', readonly: readonly, force_for_new_devices: force_for_new_devices)
      # match(type: 'development', app_identifier: 'com.frandepascuali.time', readonly: readonly, force_for_new_devices: force_for_new_devices)
  end
  
  desc 'Fetch distribution certificates'
  lane :fetch_distribution_certificates do |options|
      readonly = options[:readonly].nil? ? true : options[:readonly]
      force_for_new_devices = options[:force_for_new_devices].nil? ? false : options[:force_for_new_devices]

      match(type: 'adhoc', app_identifier: 'com.thacherhussain.slytherin', readonly: readonly, force_for_new_devices: force_for_new_devices)
      # match(type: 'adhoc', app_identifier: 'com.frandepascuali.time.beta', readonly: readonly, force_for_new_devices: force_for_new_devices)
      # match(type: 'appstore', app_identifier: 'com.frandepascuali.time', readonly: readonly, force_for_new_devices: force_for_new_devices)
  end
end
